= Module

Go code is grouped into packages, and packages are grouped into modules. +
Your module specifies dependencies needed to run your code, including the Go version and the set of other modules it requires.

== Create a module

You create a module using the https://go.dev/ref/mod#go-mod-init[`go mod init`] command: `go mod init` module_path.

The module path must be a path from which the module can be downloaded by Go tools. +
It identifies the module and acts as a prefix for package import paths within the module.

[tabs]
======
Go::
+
[source, sh]
.Create the module
----
mkdir greetings
cd greetings
go mod init example.com/greetings
----
+
[source, go]
.Implement the functionality
----
package greetings

import "fmt"

func Hello(name string) string { <1> <2>
    message := fmt.Sprintf("Hi, %v. Welcome!", name) <3>
    return message
}
----
<1> A function whose name starts with a capital letter can be called by a function that is not in the same package. +
This is known as an exported name. +
[red]#This is in my opinion not a good idea: an access modifier or an export statment is clearer.#
<2> A function declaration is of the form: `func function_name(parameter_name parameter_type) return_type`.
<3> `:=` declares and initializes a variable in one line. +
The type is inferred. +
This is an alternative to : +
`var message string` +
`message = fmt.Sprintf("Hi, %v. Welcome!", name)`

Java::
+
[source, java]
----
package greeting;

public class Hello {
    static String hello(name String) {
        var message = String.format("Hi, %s. Welcome!", name);
        return message;
    }
}
----
======

== Call the code from another module

[tabs]
======
Go::
+
[source, sh]
.Create the module
----
mkdir hello
cd hello
go mod init example.com/hello
----
+
[source, go]
.Implement the functionality
----
package main <1>

import (
    "fmt"
    "example.com/greetings"
)

func main() {
    message := greetings.Hello("Aowss")
    fmt.Println(message)
}
----
<1> Executable code must be in the `main` package
+
[source, sh]
.Update the `hello` module to use the local `greetings` module
----
go mod edit -replace example.com/greetings=../greetings <1>
go mod tidy <2>
----
<1> Use the local module
<2> Synchronize `go.mod` file and source code.
+
[source, sh]
.`hello/go.mod` file
----
include::{sourcedir}/3.module/go/hello/go.mod[]
----

Java::
======

== Run the program

[tabs]
======
Go::
+
[source, sh]
----
cd hello
go run .
----
======